name: BottomNav
description: A simple Flutter app with BLoC-based bottom navigation
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/ic_home.png
    - assets/icons/ic_quran.png
    - assets/icons/ic_tasbih.png
    - assets/icons/ic_mosque.png
    - assets/icons/ic_features.png